version: "3.8"

x-service-volumes: &service-volumes
  - ./app:/app/:rw,cached
  - ./data/web:/vol/web

x-database-variables: &database-variables
  POSTGRES_USER: djangouser
  POSTGRES_PASSWORD: djangopostgres
  POSTGRES_DB: helloworld
  POSTGRES_HOST: postgres

x-app-variables: &app-variables
  <<: *database-variables
  POSTGRES_HOST: postgres
  DEBUG: 1
  SECRET_KEY: "6g^*cv_k@y+m-5@wo!=7df-qel@h3)6(9&t8$#)th97l9oyqea"

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db && 
      python manage.py migrate  &&           
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes: *service-volumes
    environment: *app-variables
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment: *database-variables
    ports:
      - "5432"

volumes:
  db-data:
